
export const Texts = {
    email:'email',
    password:'password',
    login:'login',
    signUp:'signUp',
    username:'username',
    homePage:'homePage',
    settings:'settings',
    addNew:'addNew',
    add:'add',
    shoppingType:'shoppingType',
    date:'sate',
    price:'price',
    explanation:'explanation',
    delete:'delete',
    colorTheme:'colorTheme',
    dark:'dark',
    light:'Llght',
    language:'language',
    english:'english',
    turkish:'turkish',
    signOut:'signOut',   
};
